// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Commit struct {
	Title        sql.NullString `json:"title"`
	CommitID     int32          `json:"commit_id"`
	UserID       sql.NullInt32  `json:"user_id"`
	TaskID       sql.NullInt32  `json:"task_id"`
	Comment      sql.NullString `json:"comment"`
	Category     sql.NullString `json:"category"`
	SupervisorID sql.NullInt32  `json:"supervisor_id"`
}

type Task struct {
	ID         int32          `json:"id"`
	Name       sql.NullString `json:"name"`
	Finished   sql.NullBool   `json:"finished"`
	Supervisor sql.NullInt32  `json:"supervisor"`
	CreatedAt  time.Time      `json:"created_at"`
	Category   sql.NullString `json:"category"`
}

type User struct {
	ID         int32          `json:"id"`
	FullName   sql.NullString `json:"full_name"`
	CreatedAt  time.Time      `json:"created_at"`
	Supervisor sql.NullBool   `json:"supervisor"`
	Commits    sql.NullInt32  `json:"commits"`
}
